### ISSUE TITLE
Content is scaled

### ISSUE THREAD

**Issue by SzymonMrozek** [iBlacksus/BSStackView#1]
Hello iBlacksus, you've created really nice controller, but is there any way to set BSStackView constraints and do not have content scaled? I know it needs an empty space for animations, but maybe if I'm not using up/down animation subviews should have full height?

**Comment by iBlacksus** [comment]
Hi,
You can customize constraints in `stackView.contraintsConfigurator`. Try to set `stackView.contraintsConfigurator.top = 0` and `stackView.contraintsConfigurator.bottom = 0`

**Comment by SzymonMrozek** [comment]
Works, thanks!
